feat(template): optimization cicd
unnecessary ci when job_release_please

cleanup a tag release when job_manually_release

diff --git a/template/.github/workflows/cicd.yaml b/template/.github/workflows/cicd.yaml
--- a/template/.github/workflows/cicd.yaml
+++ b/template/.github/workflows/cicd.yaml
@@ -15,6 +15,7 @@ on:{% if crate_type == "bin" %}
     branches: [main]
 
   pull_request:
+    # https://github.com/orgs/community/discussions/25161#discussioncomment-3246673
     paths: [".cargo/**", "src/**", "tests/**", "Cargo.*", "CHANGELOG*"]
     branches: [main]
 
@@ -46,6 +47,8 @@ jobs:{% if crate_type == "bin" %}
 {%- raw %}
   ci:
     name: Patrol
+    needs: [release_please]
+    if: ${{ !failure() && !cancelled() && !needs.release_please.outputs.created }}
     runs-on: ${{ matrix.os }}
     strategy:
       fail-fast: false
@@ -80,6 +83,7 @@ jobs:{% if crate_type == "bin" %}
   build:
     name: Build ${{ matrix.target }}
     needs: [ci]
+    if: ${{ !failure() && !cancelled() }}
     runs-on: ${{ matrix.os }}
 
     strategy:
@@ -117,6 +121,20 @@ jobs:{% if crate_type == "bin" %}
       - name: Prexec
         run: |
           ########## script ##########
+          # check ci status
+          case "${{ needs.ci.result }}" in
+            'success')
+              echo "success: ci passed"
+              ;;
+            'skipped')
+              echo "warn: skipped ci triggered by release_please.created"
+              ;;
+            *)
+              echo "error: ??need cancel??"
+              exit 1
+              ;;
+          esac
+
           case "${{ matrix.target }}" in
             *'-musl')
               echo "+ install musl-tools"
@@ -136,6 +154,7 @@ jobs:{% if crate_type == "bin" %}
           echo "CRATE_VERSION=$(echo $cargo_metadata | jq -r ".packages[0].version")" | tee -a "$GITHUB_ENV"
 
           cargo update
+
       - name: Build ${{ env.CRATE_NAME }} ${{ env.CRATE_VERSION }}
         run: |
           $BUILD_CMD build --locked --release --target="${{ matrix.target }}"
@@ -189,26 +208,39 @@ jobs:{% if crate_type == "bin" %}
   manually_release:
     name: Manually release
     needs: [build]
-    if: contains(github.event_name, 'workflow_dispatch')
+    if: ${{ !failure() && !cancelled() && contains(github.event_name, 'workflow_dispatch') }}
     runs-on: ubuntu-latest
     permissions:
       contents: write
     steps:
       - uses: actions/download-artifact@v3
+
+      - name: Cleanup a ${{ inputs.tag_name }} release
+        env:
+          GITHUB_TOKEN: ${{ github.token }}
+        run: |
+          ########## script ##########
+          endpoint="repos/${{ github.repository }}/git/refs/tags/${{ inputs.tag_name }}"
+          gh api "$endpoint" > /dev/null && {
+            gh api "$endpoint" -X DELETE && echo "DELETE tag ${{ inputs.tag_name }}"
+
+            release_id="$(gh api "repos/${{ github.repository }}/releases/tags/${{ inputs.tag_name }}" --jq '.id' 2>/dev/null)"
+            [[ -n "$release_id" ]] && gh api "repos/${{ github.repository }}/releases/${release_id}" -X DELETE && echo "DELETE releases $release_id"
+          }
+          :
+
       - uses: softprops/action-gh-release@v1
         with:
           generate_release_notes: true
           prerelease: ${{ inputs.prerelease }}
           tag_name: ${{ inputs.tag_name }}
-          fail_on_unmatched_files: true
           files: |
-            artifact/*.tar.gz
-            artifact/*.zip
+            artifact/*
 
   automatic_release:
     name: Automatic release
     needs: [release_please, build]
-    if: needs.release_please.outputs.created
+    if: ${{ !failure() && !cancelled() && needs.release_please.outputs.created }}
     runs-on: ubuntu-latest
     permissions:
       contents: write
@@ -216,9 +248,8 @@ jobs:{% if crate_type == "bin" %}
       - uses: actions/download-artifact@v3
       - uses: softprops/action-gh-release@v1
         with:
+          prerelease: false
           tag_name: ${{ needs.release_please.outputs.tag_name }}
-          fail_on_unmatched_files: true
           files: |
-            artifact/*.tar.gz
-            artifact/*.zip
+            artifact/*
 {% endraw %}{%- endif %}
